# Generated by Django 5.0.1 on 2024-01-24 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassCard',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='passcard', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True, verbose_name='день')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='subject', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='преподаватель')),
                ('name', models.CharField(max_length=50, verbose_name='названиe')),
                ('passcard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject', to='core.passcard', verbose_name='зачетная книжка')),
                ('schedule', models.ManyToManyField(related_name='subject', to='core.schedule', verbose_name='расписание')),
            ],
        ),
    ]
