stages:
  - build
  - test

build:
  stage: build
  script:
    echo "build!"

flake8:
  stage: test
  script:
    - docker run --rm -i $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME bash -c "
      flake8 users"
  retry: 2

test:
  stage: test
  script:
    echo "test!"