image: python:3.10

before_script:
  - pip install -r requirements.txt

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd src
    - python manage.py migrate
  retry: 2

flake8:
  stage: test
  script:
    - flake8
  retry: 2

test:
  stage: test
  script:
    - coverage run src/manage.py test
    - coverage report
  retry: 2