image: python:3.10

stages:
  - build
  - test

build:
  stage: build
  script:
    - pip install -r requirements.txt
    - cd src
    - python manage.py migrate
  retry: 2

flake8:
  stage: test
  script:
    - pip install flake8
    - pip install flake8-commas
    - pip install flake8-quotes
    - pip install flake8-string-format
    - pip install flake8-isort
    - flake8
  retry: 2

test:
  stage: test
  script:
    - cd src
    - python manage.py test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  retry: 2