image: ubuntu:20.04

stages:
  - build
  - test

before_script:
  - pip install -r requirements.txt

job_build:
  stage: build
  script:
    - echo "Building the project"
    - python manage.py collectstatic --noinput

job_test:
  stage: test
  script:
    - echo "Running tests"
    - python manage.py test
