# Generated by Django 5.0.1 on 2024-01-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ST', 'Студент'), ('TC', 'Учитель')], default='ST', max_length=2, verbose_name='роль'),
        ),
    ]
