# Generated by Django 5.0.1 on 2024-02-03 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='задание')),
                ('mark', models.IntegerField(blank=True, verbose_name='оценка')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='core.subject', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'домашнее задание',
            },
        ),
    ]
