# Generated by Django 5.0.1 on 2024-02-06 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='предмет')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject', to=settings.AUTH_USER_MODEL, verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='дата')),
                ('subjects', models.ManyToManyField(related_name='schedule', to='education.subject', verbose_name='предметы')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'расписания',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='задание')),
                ('mark', models.IntegerField(blank=True, verbose_name='оценка')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='education.subject', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'домашнее задание',
            },
        ),
    ]
