name: GitHub Actions
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test
        run: |
          cd src
          ./manage.py test
