name: GitHub Actions
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          cd src
          python manage.py migrate
